name: quran
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ">=3.6.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  http: ^1.6.0
  intl: ^0.17.0
  location: ^5.0.3
  url_launcher: ^6.1.14
  sqflite: ^2.4.1
  google_fonts: ^6.2.1
  carousel_slider: ^5.0.0
  flutter_bloc: ^9.1.0
  font_awesome_flutter: ^10.7.0
  dio: ^5.8.0+1
  geolocator: ^13.0.3

  firebase_core: ^4.7.0
  firebase_auth: ^6.4.0
  shared_preferences: ^2.5.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/img_4.png"

flutter:
  uses-material-design: true
  assets:
    - assets/